=begin
#SpatioAPI

#The REST API that owns every resource in your Spatio workspace: notes, sheets, slides, tasks, calendar events, mail, chat, files, and contacts. SpatioMCP wraps this API; Spatio Desktop reads from it. You can call it directly from your own code.  All requests must be authenticated with a Personal Access Token (`Authorization: Bearer pat_...`) or an OAuth 2.1 access token, and use HTTPS.  Official SDKs (MIT, generated from this spec on every release):  - TypeScript: https://github.com/spatio-labs/spatio-ts (`npm install @spatio-labs/spatio-ts`) - Python: https://github.com/spatio-labs/spatio-py (`pip install spatio-sdk`) - Go: https://github.com/spatio-labs/spatio-go (`go get github.com/spatio-labs/spatio-go`)  This specification is generated from the platform-service Go source on every push to `main`. The spec, not hand-written documentation, is the source of truth: server stubs and SDKs are generated from it, and any drift between the spec and the running service fails CI. 

The version of the OpenAPI document: v1
Contact: hello@spatio.app
Generated by: https://openapi-generator.tech
Generator version: 7.22.0

=end

require 'spec_helper'
require 'json'

# Unit tests for Spatio::ContactsApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'ContactsApi' do
  before do
    # run before each test
    @api_instance = Spatio::ContactsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of ContactsApi' do
    it 'should create an instance of ContactsApi' do
      expect(@api_instance).to be_instance_of(Spatio::ContactsApi)
    end
  end

  # unit tests for assign_contact_category
  # Assign a category to a contact.
  # @param id 
  # @param assign_contact_category_request 
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'assign_contact_category test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for create_contact
  # Create a contact.
  # @param create_contact_request 
  # @param [Hash] opts the optional parameters
  # @return [Contact]
  describe 'create_contact test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for create_contact_category
  # Create a contact category.
  # @param create_contact_category_request 
  # @param [Hash] opts the optional parameters
  # @return [ContactCategory]
  describe 'create_contact_category test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for delete_contact
  # Delete a contact.
  # @param id 
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'delete_contact test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for delete_contact_category
  # Delete a category.
  # @param id 
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'delete_contact_category test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_contact
  # Fetch a contact.
  # @param id 
  # @param [Hash] opts the optional parameters
  # @return [Contact]
  describe 'get_contact test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for list_contact_categories
  # List contact categories. Requires &#x60;organization_id&#x60; query param.
  # @param organization_id 
  # @param [Hash] opts the optional parameters
  # @return [ContactCategoryListResponse]
  describe 'list_contact_categories test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for list_contact_providers
  # List supported contact providers (native + OAuth-connected).
  # @param [Hash] opts the optional parameters
  # @return [ContactProviderListResponse]
  describe 'list_contact_providers test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for list_contacts
  # List the caller&#39;s contacts (across providers).
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :limit 
  # @option opts [String] :provider 
  # @option opts [String] :search 
  # @return [ContactListResponse]
  describe 'list_contacts test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for unassign_contact_category
  # Remove a category from a contact.
  # @param id 
  # @param category_id 
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'unassign_contact_category test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for update_contact
  # Update a contact.
  # @param id 
  # @param update_contact_request 
  # @param [Hash] opts the optional parameters
  # @return [Contact]
  describe 'update_contact test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for update_contact_category
  # Update a category.
  # @param id 
  # @param update_contact_category_request 
  # @param [Hash] opts the optional parameters
  # @return [ContactCategory]
  describe 'update_contact_category test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
