=begin
#SpatioAPI

#The REST API that owns every resource in your Spatio workspace: notes, sheets, slides, tasks, calendar events, mail, chat, files, and contacts. SpatioMCP wraps this API; Spatio Desktop reads from it. You can call it directly from your own code.  All requests must be authenticated with a Personal Access Token (`Authorization: Bearer pat_...`) or an OAuth 2.1 access token, and use HTTPS.  Official SDKs (MIT, generated from this spec on every release):  - TypeScript: https://github.com/spatio-labs/spatio-ts (`npm install @spatio-labs/spatio-ts`) - Python: https://github.com/spatio-labs/spatio-py (`pip install spatio-sdk`) - Go: https://github.com/spatio-labs/spatio-go (`go get github.com/spatio-labs/spatio-go`)  This specification is generated from the platform-service Go source on every push to `main`. The spec, not hand-written documentation, is the source of truth: server stubs and SDKs are generated from it, and any drift between the spec and the running service fails CI. 

The version of the OpenAPI document: v1
Contact: hello@spatio.app
Generated by: https://openapi-generator.tech
Generator version: 7.22.0

=end

require 'spec_helper'
require 'json'

# Unit tests for Spatio::InboxApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'InboxApi' do
  before do
    # run before each test
    @api_instance = Spatio::InboxApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of InboxApi' do
    it 'should create an instance of InboxApi' do
      expect(@api_instance).to be_instance_of(Spatio::InboxApi)
    end
  end

  # unit tests for get_inbox_counts
  # Per-bucket unread counts.
  # @param [Hash] opts the optional parameters
  # @return [InboxCounts]
  describe 'get_inbox_counts test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for list_inbox
  # Unified inbox feed across mail, channel mentions, DMs, system notifications.
  # @param [Hash] opts the optional parameters
  # @option opts [String] :category 
  # @option opts [Boolean] :unread_only 
  # @option opts [Integer] :limit 
  # @return [InboxListResponse]
  describe 'list_inbox test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for mark_inbox_item_read
  # Mark a single inbox item as read.
  # @param id 
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'mark_inbox_item_read test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for workspace_get_inbox_counts
  # @param org 
  # @param workspace 
  # @param [Hash] opts the optional parameters
  # @return [Hash<String, Object>]
  describe 'workspace_get_inbox_counts test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for workspace_list_inbox
  # @param org 
  # @param workspace 
  # @param [Hash] opts the optional parameters
  # @return [Hash<String, Object>]
  describe 'workspace_list_inbox test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for workspace_mark_inbox_item_read
  # @param org 
  # @param workspace 
  # @param id 
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'workspace_mark_inbox_item_read test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
