=begin
#SpatioAPI

#The REST API that owns every resource in your Spatio workspace: notes, sheets, slides, tasks, calendar events, mail, chat, files, and contacts. SpatioMCP wraps this API; Spatio Desktop reads from it. You can call it directly from your own code.  All requests must be authenticated with a Personal Access Token (`Authorization: Bearer pat_...`) or an OAuth 2.1 access token, and use HTTPS.  Official SDKs (MIT, generated from this spec on every release):  - TypeScript: https://github.com/spatio-labs/spatio-ts (`npm install @spatio/sdk-ts`) - Python: https://github.com/spatio-labs/spatio-py (`pip install spatio-sdk`) - Go: https://github.com/spatio-labs/spatio-go (`go get github.com/spatio-labs/spatio-go`)  This specification is generated from the platform-service Go source on every push to `main`. The spec, not hand-written documentation, is the source of truth: server stubs and SDKs are generated from it, and any drift between the spec and the running service fails CI. 

The version of the OpenAPI document: v1
Contact: hello@spatio.app
Generated by: https://openapi-generator.tech
Generator version: 7.22.0

=end

require 'spec_helper'
require 'json'

# Unit tests for Spatio::KeybindingsApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'KeybindingsApi' do
  before do
    # run before each test
    @api_instance = Spatio::KeybindingsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of KeybindingsApi' do
    it 'should create an instance of KeybindingsApi' do
      expect(@api_instance).to be_instance_of(Spatio::KeybindingsApi)
    end
  end

  # unit tests for delete_key_binding
  # Reset a binding to its platform default.
  # @param id 
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'delete_key_binding test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_default_key_bindings
  # Platform default key bindings (no user customizations applied).
  # @param [Hash] opts the optional parameters
  # @return [KeyBindingListResponse]
  describe 'get_default_key_bindings test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for list_key_bindings
  # User&#39;s merged key bindings (defaults + customizations).
  # @param [Hash] opts the optional parameters
  # @return [KeyBindingListResponse]
  describe 'list_key_bindings test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for reset_all_key_bindings
  # Reset every customization to its platform default.
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'reset_all_key_bindings test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for update_key_binding
  # Create or update a user key-binding customization.
  # @param id 
  # @param update_key_binding_request 
  # @param [Hash] opts the optional parameters
  # @return [KeyBinding]
  describe 'update_key_binding test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for validate_key_binding
  # Check whether a proposed binding conflicts with existing ones.
  # @param validate_key_binding_request 
  # @param [Hash] opts the optional parameters
  # @return [ValidateKeyBindingResponse]
  describe 'validate_key_binding test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
