=begin
#SpatioAPI

#The REST API that owns every resource in your Spatio workspace: notes, sheets, slides, tasks, calendar events, mail, chat, files, and contacts. SpatioMCP wraps this API; Spatio Desktop reads from it. You can call it directly from your own code.  All requests must be authenticated with a Personal Access Token (`Authorization: Bearer pat_...`) or an OAuth 2.1 access token, and use HTTPS.  Official SDKs (MIT, generated from this spec on every release):  - TypeScript: https://github.com/spatio-labs/spatio-ts (`npm install @spatio-labs/spatio-ts`) - Python: https://github.com/spatio-labs/spatio-py (`pip install spatio-sdk`) - Go: https://github.com/spatio-labs/spatio-go (`go get github.com/spatio-labs/spatio-go`)  This specification is generated from the platform-service Go source on every push to `main`. The spec, not hand-written documentation, is the source of truth: server stubs and SDKs are generated from it, and any drift between the spec and the running service fails CI. 

The version of the OpenAPI document: v1
Contact: hello@spatio.app
Generated by: https://openapi-generator.tech
Generator version: 7.22.0

=end

require 'spec_helper'
require 'json'

# Unit tests for Spatio::OrganizationsApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'OrganizationsApi' do
  before do
    # run before each test
    @api_instance = Spatio::OrganizationsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of OrganizationsApi' do
    it 'should create an instance of OrganizationsApi' do
      expect(@api_instance).to be_instance_of(Spatio::OrganizationsApi)
    end
  end

  # unit tests for accept_organization_invitation
  # Accept an invitation to this organization.
  # @param org 
  # @param accept_organization_invitation_request 
  # @param [Hash] opts the optional parameters
  # @return [Hash<String, Object>]
  describe 'accept_organization_invitation test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for add_organization_member
  # Add a member directly (skips invitation flow).
  # @param org 
  # @param add_organization_member_request 
  # @param [Hash] opts the optional parameters
  # @return [Hash<String, Object>]
  describe 'add_organization_member test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for create_organization
  # Create an organization.
  # @param create_organization_request 
  # @param [Hash] opts the optional parameters
  # @return [Hash<String, Object>]
  describe 'create_organization test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for create_organization_concept
  # Create an org-brain concept (admin+ only).
  # @param org 
  # @param request_body 
  # @param [Hash] opts the optional parameters
  # @return [Hash<String, Object>]
  describe 'create_organization_concept test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for create_organization_custom_role
  # Create a custom role (admin+ only).
  # @param org 
  # @param request_body 
  # @param [Hash] opts the optional parameters
  # @return [Hash<String, Object>]
  describe 'create_organization_custom_role test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for create_organization_invitation
  # Invite a user to the organization.
  # Pending invitations count toward seat cap. Free-tier callers at the cap receive a &#x60;402&#x60; with billing-upgrade payload; paid-tier auto-scales the Stripe quantity. 
  # @param org 
  # @param create_organization_invitation_request 
  # @param [Hash] opts the optional parameters
  # @return [OrganizationInvitation]
  describe 'create_organization_invitation test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for create_organization_workspace
  # Create a workspace inside an organization.
  # Requires the &#x60;OrgActionCreateWorkspace&#x60; action permission. Slug collisions auto-suffix (&#x60;-2&#x60;, &#x60;-3&#x60;, ...). 
  # @param org 
  # @param create_workspace_request 
  # @param [Hash] opts the optional parameters
  # @return [WorkspaceEnvelope]
  describe 'create_organization_workspace test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for delete_organization
  # Delete an organization.
  # @param org Organization id or slug.
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'delete_organization test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for delete_organization_concept
  # Delete a concept (admin+ only).
  # @param org 
  # @param slug 
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'delete_organization_concept test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for delete_organization_custom_role
  # Delete a custom role (admin+ only).
  # @param org 
  # @param role_id 
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'delete_organization_custom_role test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for delete_organization_logo
  # Delete the organization logo.
  # @param org 
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'delete_organization_logo test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_organization
  # Fetch a single organization.
  # **Wire format note:** response uses PascalCase keys (&#x60;ID&#x60;, &#x60;Name&#x60;, &#x60;Slug&#x60;, ...) — distinct from the rest of the SpatioAPI&#39;s camelCase convention. Documented as-is; a future cleanup will harmonize. 
  # @param org Organization id or slug.
  # @param [Hash] opts the optional parameters
  # @return [OrganizationDetailLegacy]
  describe 'get_organization test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_organization_concept
  # Fetch a concept.
  # @param org 
  # @param slug 
  # @param [Hash] opts the optional parameters
  # @return [Hash<String, Object>]
  describe 'get_organization_concept test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for list_my_organizations
  # List the caller&#39;s organizations.
  # @param [Hash] opts the optional parameters
  # @return [OrganizationListResponse]
  describe 'list_my_organizations test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for list_organization_audit_log
  # Read the organization audit log (admin / billing-admin only).
  # @param org 
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :limit 
  # @option opts [String] :cursor 
  # @return [Hash<String, Object>]
  describe 'list_organization_audit_log test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for list_organization_concepts
  # List org-brain concepts (curated knowledge surfaced to agents).
  # @param org 
  # @param [Hash] opts the optional parameters
  # @return [Hash<String, Object>]
  describe 'list_organization_concepts test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for list_organization_custom_roles
  # List custom roles defined on the organization.
  # @param org 
  # @param [Hash] opts the optional parameters
  # @return [Hash<String, Object>]
  describe 'list_organization_custom_roles test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for list_organization_invitations
  # List pending invitations for an organization.
  # @param org 
  # @param [Hash] opts the optional parameters
  # @return [OrganizationInvitationListResponse]
  describe 'list_organization_invitations test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for list_organization_members
  # List members of an organization.
  # @param org 
  # @param [Hash] opts the optional parameters
  # @return [OrganizationMemberListResponse]
  describe 'list_organization_members test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for list_organization_workspaces
  # List workspaces in an organization.
  # @param org 
  # @param [Hash] opts the optional parameters
  # @return [WorkspaceListResponse]
  describe 'list_organization_workspaces test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for remove_organization_member
  # Remove a member from the organization.
  # @param org 
  # @param member_id 
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'remove_organization_member test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for resend_organization_invitation
  # Revoke and reissue an invitation with a fresh token.
  # @param org 
  # @param invitation_id 
  # @param [Hash] opts the optional parameters
  # @return [OrganizationInvitation]
  describe 'resend_organization_invitation test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for revoke_organization_invitation
  # Revoke a pending invitation.
  # @param org 
  # @param invitation_id 
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'revoke_organization_invitation test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for update_organization
  # Update organization metadata.
  # @param org Organization id or slug.
  # @param update_organization_request 
  # @param [Hash] opts the optional parameters
  # @return [Hash<String, Object>]
  describe 'update_organization test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for update_organization_concept
  # Update a concept (admin+ only).
  # @param org 
  # @param slug 
  # @param request_body 
  # @param [Hash] opts the optional parameters
  # @return [Hash<String, Object>]
  describe 'update_organization_concept test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for update_organization_custom_role
  # Update a custom role (admin+ only).
  # @param org 
  # @param role_id 
  # @param request_body 
  # @param [Hash] opts the optional parameters
  # @return [Hash<String, Object>]
  describe 'update_organization_custom_role test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for update_organization_member
  # Update a member&#39;s role.
  # @param org 
  # @param member_id 
  # @param update_organization_member_request 
  # @param [Hash] opts the optional parameters
  # @return [Hash<String, Object>]
  describe 'update_organization_member test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for upload_organization_logo
  # Upload (or replace) the organization logo. Multipart.
  # @param org 
  # @param [Hash] opts the optional parameters
  # @option opts [File] :file 
  # @return [Hash<String, Object>]
  describe 'upload_organization_logo test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
