=begin
#SpatioAPI

#The REST API that owns every resource in your Spatio workspace: notes, sheets, slides, tasks, calendar events, mail, chat, files, and contacts. SpatioMCP wraps this API; Spatio Desktop reads from it. You can call it directly from your own code.  All requests must be authenticated with a Personal Access Token (`Authorization: Bearer pat_...`) or an OAuth 2.1 access token, and use HTTPS.  Official SDKs (MIT, generated from this spec on every release):  - TypeScript: https://github.com/spatio-labs/spatio-ts (`npm install @spatio/sdk-ts`) - Python: https://github.com/spatio-labs/spatio-py (`pip install spatio-sdk`) - Go: https://github.com/spatio-labs/spatio-go (`go get github.com/spatio-labs/spatio-go`)  This specification is generated from the platform-service Go source on every push to `main`. The spec, not hand-written documentation, is the source of truth: server stubs and SDKs are generated from it, and any drift between the spec and the running service fails CI. 

The version of the OpenAPI document: v1
Contact: hello@spatio.app
Generated by: https://openapi-generator.tech
Generator version: 7.22.0

=end

require 'spec_helper'
require 'json'

# Unit tests for Spatio::PersonalAccessTokensApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'PersonalAccessTokensApi' do
  before do
    # run before each test
    @api_instance = Spatio::PersonalAccessTokensApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of PersonalAccessTokensApi' do
    it 'should create an instance of PersonalAccessTokensApi' do
      expect(@api_instance).to be_instance_of(Spatio::PersonalAccessTokensApi)
    end
  end

  # unit tests for create_personal_access_token
  # Create a new PAT. The full token is returned only once on creation; the API never reveals the secret again. 
  # @param create_pat_request 
  # @param [Hash] opts the optional parameters
  # @return [CreatePATResponse]
  describe 'create_personal_access_token test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for list_available_pat_scopes
  # List the scope strings PATs can be issued with.
  # @param [Hash] opts the optional parameters
  # @return [PATScopesResponse]
  describe 'list_available_pat_scopes test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for list_personal_access_tokens
  # List the caller&#39;s personal access tokens (with available scopes).
  # @param [Hash] opts the optional parameters
  # @return [PATListResponse]
  describe 'list_personal_access_tokens test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for revoke_personal_access_token
  # Revoke a PAT.
  # @param id 
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'revoke_personal_access_token test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for update_personal_access_token
  # Rename or re-describe a PAT (scopes are immutable).
  # @param id 
  # @param update_pat_request 
  # @param [Hash] opts the optional parameters
  # @return [PersonalAccessToken]
  describe 'update_personal_access_token test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for workspace_create_pat
  # @param org 
  # @param workspace 
  # @param request_body 
  # @param [Hash] opts the optional parameters
  # @return [Hash<String, Object>]
  describe 'workspace_create_pat test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for workspace_list_pats
  # @param org 
  # @param workspace 
  # @param [Hash] opts the optional parameters
  # @return [Hash<String, Object>]
  describe 'workspace_list_pats test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for workspace_revoke_pat
  # @param org 
  # @param workspace 
  # @param id 
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'workspace_revoke_pat test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for workspace_update_pat
  # @param org 
  # @param workspace 
  # @param id 
  # @param request_body 
  # @param [Hash] opts the optional parameters
  # @return [Hash<String, Object>]
  describe 'workspace_update_pat test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
