=begin
#SpatioAPI

#The REST API that owns every resource in your Spatio workspace: notes, sheets, slides, tasks, calendar events, mail, chat, files, and contacts. SpatioMCP wraps this API; Spatio Desktop reads from it. You can call it directly from your own code.  All requests must be authenticated with a Personal Access Token (`Authorization: Bearer pat_...`) or an OAuth 2.1 access token, and use HTTPS.  Official SDKs (MIT, generated from this spec on every release):  - TypeScript: https://github.com/spatio-labs/spatio-ts (`npm install @spatio/sdk-ts`) - Python: https://github.com/spatio-labs/spatio-py (`pip install spatio-sdk`) - Go: https://github.com/spatio-labs/spatio-go (`go get github.com/spatio-labs/spatio-go`)  This specification is generated from the platform-service Go source on every push to `main`. The spec, not hand-written documentation, is the source of truth: server stubs and SDKs are generated from it, and any drift between the spec and the running service fails CI. 

The version of the OpenAPI document: v1
Contact: hello@spatio.app
Generated by: https://openapi-generator.tech
Generator version: 7.22.0

=end

require 'spec_helper'
require 'json'

# Unit tests for Spatio::SlidesApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'SlidesApi' do
  before do
    # run before each test
    @api_instance = Spatio::SlidesApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of SlidesApi' do
    it 'should create an instance of SlidesApi' do
      expect(@api_instance).to be_instance_of(Spatio::SlidesApi)
    end
  end

  # unit tests for create_presentation
  # Create a presentation.
  # Creates a new deck under the target account. Target resolution mirrors &#x60;POST /v1/notes&#x60; and &#x60;/v1/sheets&#x60;: body &#x60;accountId&#x60; → &#x60;?accountId&#x3D;&#x60; → body &#x60;provider&#x60; → &#x60;?provider&#x3D;&#x60; → caller&#39;s single connected account (errors with &#x60;ambiguous_account&#x60; otherwise). The new deck is auto-seeded with one blank slide so the renderer has something to display immediately. 
  # @param create_presentation_request 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :account_id Connected-account row id. Selects which provider account this request targets when more than one is connected. Mutually exclusive with &#x60;provider&#x60;. If omitted on a list endpoint the call fans out across every connected account. 
  # @option opts [String] :provider Provider id (e.g. &#x60;native-notes&#x60;, &#x60;notion&#x60;). Selects every connected account for the provider. Mutually exclusive with &#x60;accountId&#x60;. 
  # @option opts [String] :x_workspace_id Workspace scope for unscoped tokens. Workspace-scoped PATs and OAuth tokens carry this implicitly; for session/JWT auth without a scoped PAT, pass it explicitly. 
  # @return [Presentation]
  describe 'create_presentation test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for create_slide
  # Insert a slide.
  # @param id Presentation id.
  # @param create_slide_request 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :account_id Connected-account row id. Selects which provider account this request targets when more than one is connected. Mutually exclusive with &#x60;provider&#x60;. If omitted on a list endpoint the call fans out across every connected account. 
  # @option opts [String] :x_workspace_id Workspace scope for unscoped tokens. Workspace-scoped PATs and OAuth tokens carry this implicitly; for session/JWT auth without a scoped PAT, pass it explicitly. 
  # @return [Slide]
  describe 'create_slide test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for create_slide_element
  # Add a canvas element (text/shape/image) to a slide.
  # @param id Presentation id.
  # @param slide_id Slide id within the presentation.
  # @param create_slide_element_request 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :account_id Connected-account row id. Selects which provider account this request targets when more than one is connected. Mutually exclusive with &#x60;provider&#x60;. If omitted on a list endpoint the call fans out across every connected account. 
  # @option opts [String] :x_workspace_id Workspace scope for unscoped tokens. Workspace-scoped PATs and OAuth tokens carry this implicitly; for session/JWT auth without a scoped PAT, pass it explicitly. 
  # @return [SlideElement]
  describe 'create_slide_element test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for delete_presentation
  # Delete a presentation.
  # @param id Presentation id.
  # @param [Hash] opts the optional parameters
  # @option opts [String] :account_id Connected-account row id. Selects which provider account this request targets when more than one is connected. Mutually exclusive with &#x60;provider&#x60;. If omitted on a list endpoint the call fans out across every connected account. 
  # @option opts [String] :x_workspace_id Workspace scope for unscoped tokens. Workspace-scoped PATs and OAuth tokens carry this implicitly; for session/JWT auth without a scoped PAT, pass it explicitly. 
  # @return [SuccessFlag]
  describe 'delete_presentation test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for delete_slide
  # Delete a slide.
  # @param id Presentation id.
  # @param slide_id Slide id within the presentation.
  # @param [Hash] opts the optional parameters
  # @option opts [String] :account_id Connected-account row id. Selects which provider account this request targets when more than one is connected. Mutually exclusive with &#x60;provider&#x60;. If omitted on a list endpoint the call fans out across every connected account. 
  # @option opts [String] :x_workspace_id Workspace scope for unscoped tokens. Workspace-scoped PATs and OAuth tokens carry this implicitly; for session/JWT auth without a scoped PAT, pass it explicitly. 
  # @return [SuccessFlag]
  describe 'delete_slide test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for delete_slide_element
  # Delete a slide element.
  # @param id Presentation id.
  # @param slide_id Slide id within the presentation.
  # @param element_id Slide-element id.
  # @param [Hash] opts the optional parameters
  # @option opts [String] :account_id Connected-account row id. Selects which provider account this request targets when more than one is connected. Mutually exclusive with &#x60;provider&#x60;. If omitted on a list endpoint the call fans out across every connected account. 
  # @option opts [String] :x_workspace_id Workspace scope for unscoped tokens. Workspace-scoped PATs and OAuth tokens carry this implicitly; for session/JWT auth without a scoped PAT, pass it explicitly. 
  # @return [SuccessFlag]
  describe 'delete_slide_element test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for disable_presentation_share
  # Disable public sharing.
  # Owner-only. Subsequent public viewer requests 404.
  # @param id Presentation id.
  # @param [Hash] opts the optional parameters
  # @option opts [String] :account_id Connected-account row id. Selects which provider account this request targets when more than one is connected. Mutually exclusive with &#x60;provider&#x60;. If omitted on a list endpoint the call fans out across every connected account. 
  # @option opts [String] :x_workspace_id Workspace scope for unscoped tokens. Workspace-scoped PATs and OAuth tokens carry this implicitly; for session/JWT auth without a scoped PAT, pass it explicitly. 
  # @return [nil]
  describe 'disable_presentation_share test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for enable_presentation_share
  # Enable (or update password on) public sharing.
  # Owner-only. With &#x60;setPassword: false&#x60; (or empty body), flips the deck public without changing the password. With &#x60;setPassword: true&#x60;, applies &#x60;password&#x60; (empty clears). 
  # @param id Presentation id.
  # @param [Hash] opts the optional parameters
  # @option opts [String] :account_id Connected-account row id. Selects which provider account this request targets when more than one is connected. Mutually exclusive with &#x60;provider&#x60;. If omitted on a list endpoint the call fans out across every connected account. 
  # @option opts [String] :x_workspace_id Workspace scope for unscoped tokens. Workspace-scoped PATs and OAuth tokens carry this implicitly; for session/JWT auth without a scoped PAT, pass it explicitly. 
  # @option opts [EnableShareRequest] :enable_share_request 
  # @return [ShareSettings]
  describe 'enable_presentation_share test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for export_presentation_pdf
  # Render the presentation as a PDF.
  # Proxies to the Spatio export sidecar (Playwright). Two response modes selected via &#x60;?storage&#x3D;&#x60;:    - &#x60;stream&#x60; (default) — response body is the PDF binary     (&#x60;application/pdf&#x60;).   - &#x60;r2&#x60; — uploads the rendered PDF to R2 storage and returns     a JSON envelope with a 24-hour signed URL.  Returns &#x60;503 Service Unavailable&#x60; when the export sidecar is not configured (dev fallback to the client-side exporter). 
  # @param id Presentation id.
  # @param [Hash] opts the optional parameters
  # @option opts [String] :account_id Connected-account row id. Selects which provider account this request targets when more than one is connected. Mutually exclusive with &#x60;provider&#x60;. If omitted on a list endpoint the call fans out across every connected account. 
  # @option opts [String] :x_workspace_id Workspace scope for unscoped tokens. Workspace-scoped PATs and OAuth tokens carry this implicitly; for session/JWT auth without a scoped PAT, pass it explicitly. 
  # @option opts [String] :storage 
  # @option opts [String] :filename Sanitized base name for the downloaded PDF.
  # @option opts [ExportPDFRequest] :export_pdf_request 
  # @return [File]
  describe 'export_presentation_pdf test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for export_presentation_pptx
  # Render the presentation as a PowerPoint (.pptx) file.
  # Proxies to the Spatio export sidecar (Playwright + pptxgenjs). Each slide is screenshotted at 2× device-pixel ratio and wrapped into a PowerPoint .pptx as a full-bleed image. Visual fidelity is preserved exactly — what renders in Spatio renders identically in PowerPoint, Keynote, Google Slides — at the cost of in-PowerPoint editability of slide content. Users edit slide content back in Spatio (the source of truth), not inside PowerPoint.  Two response modes selected via &#x60;?storage&#x3D;&#x60;:    - &#x60;stream&#x60; (default) — response body is the PPTX binary     (&#x60;application/vnd.openxmlformats-officedocument.presentationml.presentation&#x60;).   - &#x60;r2&#x60; — uploads the rendered PPTX to R2 storage and returns     a JSON envelope with a 24-hour signed URL.  Returns &#x60;503 Service Unavailable&#x60; when the export sidecar is not configured. 
  # @param id Presentation id.
  # @param [Hash] opts the optional parameters
  # @option opts [String] :account_id Connected-account row id. Selects which provider account this request targets when more than one is connected. Mutually exclusive with &#x60;provider&#x60;. If omitted on a list endpoint the call fans out across every connected account. 
  # @option opts [String] :x_workspace_id Workspace scope for unscoped tokens. Workspace-scoped PATs and OAuth tokens carry this implicitly; for session/JWT auth without a scoped PAT, pass it explicitly. 
  # @option opts [String] :storage 
  # @option opts [String] :filename Sanitized base name for the downloaded PPTX.
  # @option opts [ExportPDFRequest] :export_pdf_request 
  # @return [File]
  describe 'export_presentation_pptx test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_presentation
  # Fetch one presentation.
  # @param id Presentation id.
  # @param [Hash] opts the optional parameters
  # @option opts [String] :account_id Connected-account row id. Selects which provider account this request targets when more than one is connected. Mutually exclusive with &#x60;provider&#x60;. If omitted on a list endpoint the call fans out across every connected account. 
  # @option opts [String] :x_workspace_id Workspace scope for unscoped tokens. Workspace-scoped PATs and OAuth tokens carry this implicitly; for session/JWT auth without a scoped PAT, pass it explicitly. 
  # @return [Presentation]
  describe 'get_presentation test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_presentation_share_settings
  # Fetch share settings for a presentation.
  # Owner-only. Mirror of &#x60;GET /v1/notes/{id}/share&#x60; — same shape, same fields. Returns the current public-share configuration, including the share token and computed public viewer URL when the deck is currently public. 
  # @param id Presentation id.
  # @param [Hash] opts the optional parameters
  # @option opts [String] :account_id Connected-account row id. Selects which provider account this request targets when more than one is connected. Mutually exclusive with &#x60;provider&#x60;. If omitted on a list endpoint the call fans out across every connected account. 
  # @option opts [String] :x_workspace_id Workspace scope for unscoped tokens. Workspace-scoped PATs and OAuth tokens carry this implicitly; for session/JWT auth without a scoped PAT, pass it explicitly. 
  # @return [ShareSettings]
  describe 'get_presentation_share_settings test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_public_presentation
  # Fetch a publicly shared presentation.
  # Unauthenticated. Mirror of &#x60;GET /public/notes/{token}&#x60;. The share token is the credential. For password-protected decks the password is supplied via &#x60;?password&#x3D;&#x60;; the response distinguishes \&quot;no password supplied\&quot; from \&quot;wrong password\&quot; so the viewer can render the right prompt. Unknown tokens and disabled-share decks both return &#x60;404&#x60; to prevent enumeration. 
  # @param token Opaque public-share token.
  # @param [Hash] opts the optional parameters
  # @option opts [String] :password Optional viewer password.
  # @return [Hash<String, Object>]
  describe 'get_public_presentation test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_slide
  # Fetch one slide.
  # @param id Presentation id.
  # @param slide_id Slide id within the presentation.
  # @param [Hash] opts the optional parameters
  # @option opts [String] :account_id Connected-account row id. Selects which provider account this request targets when more than one is connected. Mutually exclusive with &#x60;provider&#x60;. If omitted on a list endpoint the call fans out across every connected account. 
  # @option opts [String] :x_workspace_id Workspace scope for unscoped tokens. Workspace-scoped PATs and OAuth tokens carry this implicitly; for session/JWT auth without a scoped PAT, pass it explicitly. 
  # @return [Slide]
  describe 'get_slide test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_slide_element
  # Fetch one slide element.
  # @param id Presentation id.
  # @param slide_id Slide id within the presentation.
  # @param element_id Slide-element id.
  # @param [Hash] opts the optional parameters
  # @option opts [String] :account_id Connected-account row id. Selects which provider account this request targets when more than one is connected. Mutually exclusive with &#x60;provider&#x60;. If omitted on a list endpoint the call fans out across every connected account. 
  # @option opts [String] :x_workspace_id Workspace scope for unscoped tokens. Workspace-scoped PATs and OAuth tokens carry this implicitly; for session/JWT auth without a scoped PAT, pass it explicitly. 
  # @return [SlideElement]
  describe 'get_slide_element test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for list_presentations
  # List presentations across connected accounts.
  # Fan-out list. Returns every presentation visible to the caller across every connected slides provider. Pass &#x60;?accountId&#x3D;&#x60; or &#x60;?provider&#x3D;&#x60; to scope to a single source. 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :account_id Connected-account row id. Selects which provider account this request targets when more than one is connected. Mutually exclusive with &#x60;provider&#x60;. If omitted on a list endpoint the call fans out across every connected account. 
  # @option opts [String] :provider Provider id (e.g. &#x60;native-notes&#x60;, &#x60;notion&#x60;). Selects every connected account for the provider. Mutually exclusive with &#x60;accountId&#x60;. 
  # @option opts [String] :x_workspace_id Workspace scope for unscoped tokens. Workspace-scoped PATs and OAuth tokens carry this implicitly; for session/JWT auth without a scoped PAT, pass it explicitly. 
  # @option opts [Integer] :limit 
  # @option opts [Integer] :offset 
  # @return [PresentationListEnvelope]
  describe 'list_presentations test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for list_slide_elements
  # List the canvas elements on a slide.
  # @param id Presentation id.
  # @param slide_id Slide id within the presentation.
  # @param [Hash] opts the optional parameters
  # @option opts [String] :account_id Connected-account row id. Selects which provider account this request targets when more than one is connected. Mutually exclusive with &#x60;provider&#x60;. If omitted on a list endpoint the call fans out across every connected account. 
  # @option opts [String] :x_workspace_id Workspace scope for unscoped tokens. Workspace-scoped PATs and OAuth tokens carry this implicitly; for session/JWT auth without a scoped PAT, pass it explicitly. 
  # @return [SlideElementList]
  describe 'list_slide_elements test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for list_slides_in_presentation
  # List slides in a presentation.
  # Single-account list. Returns slides in the order set by their &#x60;position&#x60; field. 
  # @param id Presentation id.
  # @param [Hash] opts the optional parameters
  # @option opts [String] :account_id Connected-account row id. Selects which provider account this request targets when more than one is connected. Mutually exclusive with &#x60;provider&#x60;. If omitted on a list endpoint the call fans out across every connected account. 
  # @option opts [String] :x_workspace_id Workspace scope for unscoped tokens. Workspace-scoped PATs and OAuth tokens carry this implicitly; for session/JWT auth without a scoped PAT, pass it explicitly. 
  # @return [SlideList]
  describe 'list_slides_in_presentation test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for rotate_presentation_share_token
  # Rotate the share token, invalidating outstanding URLs.
  # @param id Presentation id.
  # @param [Hash] opts the optional parameters
  # @option opts [String] :account_id Connected-account row id. Selects which provider account this request targets when more than one is connected. Mutually exclusive with &#x60;provider&#x60;. If omitted on a list endpoint the call fans out across every connected account. 
  # @option opts [String] :x_workspace_id Workspace scope for unscoped tokens. Workspace-scoped PATs and OAuth tokens carry this implicitly; for session/JWT auth without a scoped PAT, pass it explicitly. 
  # @return [ShareSettings]
  describe 'rotate_presentation_share_token test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for update_presentation
  # Update presentation metadata (partial).
  # @param id Presentation id.
  # @param update_presentation_request 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :account_id Connected-account row id. Selects which provider account this request targets when more than one is connected. Mutually exclusive with &#x60;provider&#x60;. If omitted on a list endpoint the call fans out across every connected account. 
  # @option opts [String] :x_workspace_id Workspace scope for unscoped tokens. Workspace-scoped PATs and OAuth tokens carry this implicitly; for session/JWT auth without a scoped PAT, pass it explicitly. 
  # @return [Presentation]
  describe 'update_presentation test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for update_slide
  # Update a slide (partial).
  # @param id Presentation id.
  # @param slide_id Slide id within the presentation.
  # @param update_slide_request 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :account_id Connected-account row id. Selects which provider account this request targets when more than one is connected. Mutually exclusive with &#x60;provider&#x60;. If omitted on a list endpoint the call fans out across every connected account. 
  # @option opts [String] :x_workspace_id Workspace scope for unscoped tokens. Workspace-scoped PATs and OAuth tokens carry this implicitly; for session/JWT auth without a scoped PAT, pass it explicitly. 
  # @return [Slide]
  describe 'update_slide test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for update_slide_element
  # Update a slide element (partial).
  # @param id Presentation id.
  # @param slide_id Slide id within the presentation.
  # @param element_id Slide-element id.
  # @param update_slide_element_request 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :account_id Connected-account row id. Selects which provider account this request targets when more than one is connected. Mutually exclusive with &#x60;provider&#x60;. If omitted on a list endpoint the call fans out across every connected account. 
  # @option opts [String] :x_workspace_id Workspace scope for unscoped tokens. Workspace-scoped PATs and OAuth tokens carry this implicitly; for session/JWT auth without a scoped PAT, pass it explicitly. 
  # @return [SlideElement]
  describe 'update_slide_element test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
