=begin
#SpatioAPI

#The REST API that owns every resource in your Spatio workspace: notes, sheets, slides, tasks, calendar events, mail, chat, files, and contacts. SpatioMCP wraps this API; Spatio Desktop reads from it. You can call it directly from your own code.  All requests must be authenticated with a Personal Access Token (`Authorization: Bearer pat_...`) or an OAuth 2.1 access token, and use HTTPS.  Official SDKs (MIT, generated from this spec on every release):  - TypeScript: https://github.com/spatio-labs/spatio-ts (`npm install @spatio-labs/spatio-ts`) - Python: https://github.com/spatio-labs/spatio-py (`pip install spatio-sdk`) - Go: https://github.com/spatio-labs/spatio-go (`go get github.com/spatio-labs/spatio-go`)  This specification is generated from the platform-service Go source on every push to `main`. The spec, not hand-written documentation, is the source of truth: server stubs and SDKs are generated from it, and any drift between the spec and the running service fails CI. 

The version of the OpenAPI document: v1
Contact: hello@spatio.app
Generated by: https://openapi-generator.tech
Generator version: 7.22.0

=end

require 'spec_helper'
require 'json'

# Unit tests for Spatio::WorkspacesApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'WorkspacesApi' do
  before do
    # run before each test
    @api_instance = Spatio::WorkspacesApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of WorkspacesApi' do
    it 'should create an instance of WorkspacesApi' do
      expect(@api_instance).to be_instance_of(Spatio::WorkspacesApi)
    end
  end

  # unit tests for accept_workspace_invitation
  # Accept a workspace invitation by token. The signed-in user&#39;s email must match the invitation. Organization-token accept lives at &#x60;POST /v1/organizations/{org}/accept-invitation&#x60;. 
  # @param token 
  # @param [Hash] opts the optional parameters
  # @return [Hash<String, Object>]
  describe 'accept_workspace_invitation test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for add_workspace_member
  # Add a member directly (skips invitation flow).
  # @param workspace_id 
  # @param add_workspace_member_request 
  # @param [Hash] opts the optional parameters
  # @return [Hash<String, Object>]
  describe 'add_workspace_member test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for create_workspace
  # Create a workspace. Requires &#x60;organizationId&#x60; in the body — bare \&quot;personal\&quot; workspaces aren&#39;t supported on the public API. 
  # @param create_workspace_request 
  # @param [Hash] opts the optional parameters
  # @return [WorkspaceEnvelope]
  describe 'create_workspace test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for create_workspace_invitation
  # Invite a user to a workspace.
  # @param workspace_id 
  # @param create_workspace_invitation_request 
  # @param [Hash] opts the optional parameters
  # @return [WorkspaceInvitation]
  describe 'create_workspace_invitation test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_public_invitation
  # Fetch invitation details by token (unauthenticated). Used by the renderer to show invitation context before the user signs in. 
  # @param token 
  # @param [Hash] opts the optional parameters
  # @return [PublicInvitationPayload]
  describe 'get_public_invitation test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_workspace
  # Fetch a single workspace by id.
  # @param workspace_id 
  # @param [Hash] opts the optional parameters
  # @return [WorkspaceEnvelope]
  describe 'get_workspace test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for list_my_workspaces
  # List the caller&#39;s workspaces (across organizations).
  # @param [Hash] opts the optional parameters
  # @return [WorkspaceListResponse]
  describe 'list_my_workspaces test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for list_workspace_invitations
  # List pending workspace invitations.
  # @param workspace_id 
  # @param [Hash] opts the optional parameters
  # @return [WorkspaceInvitationListResponse]
  describe 'list_workspace_invitations test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for list_workspace_members
  # List members of a workspace.
  # @param workspace_id 
  # @param [Hash] opts the optional parameters
  # @return [WorkspaceMemberListResponse]
  describe 'list_workspace_members test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for remove_workspace_member
  # Remove a member from the workspace.
  # @param workspace_id 
  # @param member_id 
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'remove_workspace_member test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for revoke_workspace_invitation
  # Revoke a pending workspace invitation.
  # @param workspace_id 
  # @param invitation_id 
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'revoke_workspace_invitation test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for update_workspace
  # Update workspace metadata.
  # @param workspace_id 
  # @param update_workspace_request 
  # @param [Hash] opts the optional parameters
  # @return [WorkspaceEnvelope]
  describe 'update_workspace test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for update_workspace_member
  # Update a member&#39;s role.
  # @param workspace_id 
  # @param member_id 
  # @param update_workspace_member_request 
  # @param [Hash] opts the optional parameters
  # @return [Hash<String, Object>]
  describe 'update_workspace_member test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
