=begin
#SpatioAPI

#The REST API that owns every resource in your Spatio workspace: notes, sheets, slides, tasks, calendar events, mail, chat, files, and contacts. SpatioMCP wraps this API; Spatio Desktop reads from it. You can call it directly from your own code.  All requests must be authenticated with a Personal Access Token (`Authorization: Bearer pat_...`) or an OAuth 2.1 access token, and use HTTPS.  Official SDKs (MIT, generated from this spec on every release):  - TypeScript: https://github.com/spatio-labs/spatio-ts (`npm install @spatio/sdk-ts`) - Python: https://github.com/spatio-labs/spatio-py (`pip install spatio-sdk`) - Go: https://github.com/spatio-labs/spatio-go (`go get github.com/spatio-labs/spatio-go`)  This specification is generated from the platform-service Go source on every push to `main`. The spec, not hand-written documentation, is the source of truth: server stubs and SDKs are generated from it, and any drift between the spec and the running service fails CI. 

The version of the OpenAPI document: v1
Contact: hello@spatio.app
Generated by: https://openapi-generator.tech
Generator version: 7.22.0

=end

require 'date'
require 'time'

module Spatio
  # Per-tier capability + quota envelope. Numeric quotas use 0/-1 idioms; treat large negatives as \"unlimited.\"
  class AccountTierDetails < ApiModelBase
    attr_accessor :tier

    attr_accessor :daily_api_calls

    attr_accessor :max_connected_accounts

    attr_accessor :max_email_sends_per_day

    attr_accessor :max_notes

    attr_accessor :max_sheets

    attr_accessor :max_slides

    attr_accessor :max_files

    attr_accessor :max_tasks

    attr_accessor :max_team_members

    attr_accessor :max_workspaces

    attr_accessor :storage_gb

    attr_accessor :has_automations

    attr_accessor :has_advanced_automations

    attr_accessor :has_full_api_access

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'tier' => :'tier',
        :'daily_api_calls' => :'daily_api_calls',
        :'max_connected_accounts' => :'max_connected_accounts',
        :'max_email_sends_per_day' => :'max_email_sends_per_day',
        :'max_notes' => :'max_notes',
        :'max_sheets' => :'max_sheets',
        :'max_slides' => :'max_slides',
        :'max_files' => :'max_files',
        :'max_tasks' => :'max_tasks',
        :'max_team_members' => :'max_team_members',
        :'max_workspaces' => :'max_workspaces',
        :'storage_gb' => :'storage_gb',
        :'has_automations' => :'has_automations',
        :'has_advanced_automations' => :'has_advanced_automations',
        :'has_full_api_access' => :'has_full_api_access'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'tier' => :'String',
        :'daily_api_calls' => :'Integer',
        :'max_connected_accounts' => :'Integer',
        :'max_email_sends_per_day' => :'Integer',
        :'max_notes' => :'Integer',
        :'max_sheets' => :'Integer',
        :'max_slides' => :'Integer',
        :'max_files' => :'Integer',
        :'max_tasks' => :'Integer',
        :'max_team_members' => :'Integer',
        :'max_workspaces' => :'Integer',
        :'storage_gb' => :'Integer',
        :'has_automations' => :'Boolean',
        :'has_advanced_automations' => :'Boolean',
        :'has_full_api_access' => :'Boolean'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `Spatio::AccountTierDetails` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `Spatio::AccountTierDetails`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'tier')
        self.tier = attributes[:'tier']
      else
        self.tier = nil
      end

      if attributes.key?(:'daily_api_calls')
        self.daily_api_calls = attributes[:'daily_api_calls']
      end

      if attributes.key?(:'max_connected_accounts')
        self.max_connected_accounts = attributes[:'max_connected_accounts']
      end

      if attributes.key?(:'max_email_sends_per_day')
        self.max_email_sends_per_day = attributes[:'max_email_sends_per_day']
      end

      if attributes.key?(:'max_notes')
        self.max_notes = attributes[:'max_notes']
      end

      if attributes.key?(:'max_sheets')
        self.max_sheets = attributes[:'max_sheets']
      end

      if attributes.key?(:'max_slides')
        self.max_slides = attributes[:'max_slides']
      end

      if attributes.key?(:'max_files')
        self.max_files = attributes[:'max_files']
      end

      if attributes.key?(:'max_tasks')
        self.max_tasks = attributes[:'max_tasks']
      end

      if attributes.key?(:'max_team_members')
        self.max_team_members = attributes[:'max_team_members']
      end

      if attributes.key?(:'max_workspaces')
        self.max_workspaces = attributes[:'max_workspaces']
      end

      if attributes.key?(:'storage_gb')
        self.storage_gb = attributes[:'storage_gb']
      end

      if attributes.key?(:'has_automations')
        self.has_automations = attributes[:'has_automations']
      end

      if attributes.key?(:'has_advanced_automations')
        self.has_advanced_automations = attributes[:'has_advanced_automations']
      end

      if attributes.key?(:'has_full_api_access')
        self.has_full_api_access = attributes[:'has_full_api_access']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @tier.nil?
        invalid_properties.push('invalid value for "tier", tier cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @tier.nil?
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] tier Value to be assigned
    def tier=(tier)
      if tier.nil?
        fail ArgumentError, 'tier cannot be nil'
      end

      @tier = tier
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          tier == o.tier &&
          daily_api_calls == o.daily_api_calls &&
          max_connected_accounts == o.max_connected_accounts &&
          max_email_sends_per_day == o.max_email_sends_per_day &&
          max_notes == o.max_notes &&
          max_sheets == o.max_sheets &&
          max_slides == o.max_slides &&
          max_files == o.max_files &&
          max_tasks == o.max_tasks &&
          max_team_members == o.max_team_members &&
          max_workspaces == o.max_workspaces &&
          storage_gb == o.storage_gb &&
          has_automations == o.has_automations &&
          has_advanced_automations == o.has_advanced_automations &&
          has_full_api_access == o.has_full_api_access
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [tier, daily_api_calls, max_connected_accounts, max_email_sends_per_day, max_notes, max_sheets, max_slides, max_files, max_tasks, max_team_members, max_workspaces, storage_gb, has_automations, has_advanced_automations, has_full_api_access].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
