=begin
#SpatioAPI

#The REST API that owns every resource in your Spatio workspace: notes, sheets, slides, tasks, calendar events, mail, chat, files, and contacts. SpatioMCP wraps this API; Spatio Desktop reads from it. You can call it directly from your own code.  All requests must be authenticated with a Personal Access Token (`Authorization: Bearer pat_...`) or an OAuth 2.1 access token, and use HTTPS.  Official SDKs (MIT, generated from this spec on every release):  - TypeScript: https://github.com/spatio-labs/spatio-ts (`npm install @spatio-labs/spatio-ts`) - Python: https://github.com/spatio-labs/spatio-py (`pip install spatio-sdk`) - Go: https://github.com/spatio-labs/spatio-go (`go get github.com/spatio-labs/spatio-go`)  This specification is generated from the platform-service Go source on every push to `main`. The spec, not hand-written documentation, is the source of truth: server stubs and SDKs are generated from it, and any drift between the spec and the running service fails CI. 

The version of the OpenAPI document: v1
Contact: hello@spatio.app
Generated by: https://openapi-generator.tech
Generator version: 7.22.0

=end

require 'date'
require 'time'

module Spatio
  class BlockType
    PARAGRAPH = "paragraph".freeze
    HEADING_1 = "heading_1".freeze
    HEADING_2 = "heading_2".freeze
    HEADING_3 = "heading_3".freeze
    BULLETED_LIST_ITEM = "bulleted_list_item".freeze
    NUMBERED_LIST_ITEM = "numbered_list_item".freeze
    TO_DO = "to_do".freeze
    TOGGLE = "toggle".freeze
    CODE = "code".freeze
    QUOTE = "quote".freeze
    CALLOUT = "callout".freeze
    DIVIDER = "divider".freeze
    IMAGE = "image".freeze
    VIDEO = "video".freeze
    FILE = "file".freeze
    EMBED = "embed".freeze
    TABLE = "table".freeze
    TABLE_ROW = "table_row".freeze
    COLUMN_LIST = "column_list".freeze
    COLUMN = "column".freeze
    EQUATION = "equation".freeze
    BREADCRUMB = "breadcrumb".freeze
    TABLE_OF_CONTENTS = "table_of_contents".freeze

    def self.all_vars
      @all_vars ||= [PARAGRAPH, HEADING_1, HEADING_2, HEADING_3, BULLETED_LIST_ITEM, NUMBERED_LIST_ITEM, TO_DO, TOGGLE, CODE, QUOTE, CALLOUT, DIVIDER, IMAGE, VIDEO, FILE, EMBED, TABLE, TABLE_ROW, COLUMN_LIST, COLUMN, EQUATION, BREADCRUMB, TABLE_OF_CONTENTS].freeze
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def self.build_from_hash(value)
      new.build_from_hash(value)
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def build_from_hash(value)
      return value if BlockType.all_vars.include?(value)
      raise "Invalid ENUM value #{value} for class #BlockType"
    end
  end
end
