=begin
#SpatioAPI

#The REST API that owns every resource in your Spatio workspace: notes, sheets, slides, tasks, calendar events, mail, chat, files, and contacts. SpatioMCP wraps this API; Spatio Desktop reads from it. You can call it directly from your own code.  All requests must be authenticated with a Personal Access Token (`Authorization: Bearer pat_...`) or an OAuth 2.1 access token, and use HTTPS.  Official SDKs (MIT, generated from this spec on every release):  - TypeScript: https://github.com/spatio-labs/spatio-ts (`npm install @spatio-labs/spatio-ts`) - Python: https://github.com/spatio-labs/spatio-py (`pip install spatio-sdk`) - Go: https://github.com/spatio-labs/spatio-go (`go get github.com/spatio-labs/spatio-go`)  This specification is generated from the platform-service Go source on every push to `main`. The spec, not hand-written documentation, is the source of truth: server stubs and SDKs are generated from it, and any drift between the spec and the running service fails CI. 

The version of the OpenAPI document: v1
Contact: hello@spatio.app
Generated by: https://openapi-generator.tech
Generator version: 7.22.0

=end

require 'date'
require 'time'

module Spatio
  # A spreadsheet. Sheets belong to exactly one connected account (`accountId` + `provider`). The native provider stores sheets in the Spatio database; external providers (Google Sheets, Excel Online, etc.) round-trip through Spatio.  `data` is a free-form bag for provider-specific blobs (cell matrices, formulas, formatting). Clients that walk rows / cells should use the dedicated row + cell endpoints; `data` is only meaningful when round-tripping with an external provider that embeds its native format here. 
  class Sheet < ApiModelBase
    attr_accessor :id

    # Registered provider id (e.g. `native-sheets`).
    attr_accessor :provider

    # Connected-account row this sheet belongs to.
    attr_accessor :account_id

    # User id of the sheet owner; non-native providers leave empty.
    attr_accessor :owner_user_id

    attr_accessor :name

    attr_accessor :description

    # Free-form provider blob. Treat as opaque.
    attr_accessor :data

    attr_accessor :row_count

    attr_accessor :column_count

    # Tab count when the file contains multiple sheets.
    attr_accessor :sheet_count

    attr_accessor :is_public

    attr_accessor :is_read_only

    attr_accessor :file_size

    attr_accessor :last_accessed_at

    attr_accessor :created_at

    attr_accessor :updated_at

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'id' => :'id',
        :'provider' => :'provider',
        :'account_id' => :'accountId',
        :'owner_user_id' => :'ownerUserId',
        :'name' => :'name',
        :'description' => :'description',
        :'data' => :'data',
        :'row_count' => :'rowCount',
        :'column_count' => :'columnCount',
        :'sheet_count' => :'sheetCount',
        :'is_public' => :'isPublic',
        :'is_read_only' => :'isReadOnly',
        :'file_size' => :'fileSize',
        :'last_accessed_at' => :'lastAccessedAt',
        :'created_at' => :'createdAt',
        :'updated_at' => :'updatedAt'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'id' => :'String',
        :'provider' => :'String',
        :'account_id' => :'String',
        :'owner_user_id' => :'String',
        :'name' => :'String',
        :'description' => :'String',
        :'data' => :'Hash<String, Object>',
        :'row_count' => :'Integer',
        :'column_count' => :'Integer',
        :'sheet_count' => :'Integer',
        :'is_public' => :'Boolean',
        :'is_read_only' => :'Boolean',
        :'file_size' => :'Integer',
        :'last_accessed_at' => :'Time',
        :'created_at' => :'Time',
        :'updated_at' => :'Time'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
        :'description',
        :'file_size',
        :'last_accessed_at',
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `Spatio::Sheet` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `Spatio::Sheet`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'id')
        self.id = attributes[:'id']
      else
        self.id = nil
      end

      if attributes.key?(:'provider')
        self.provider = attributes[:'provider']
      end

      if attributes.key?(:'account_id')
        self.account_id = attributes[:'account_id']
      end

      if attributes.key?(:'owner_user_id')
        self.owner_user_id = attributes[:'owner_user_id']
      end

      if attributes.key?(:'name')
        self.name = attributes[:'name']
      else
        self.name = nil
      end

      if attributes.key?(:'description')
        self.description = attributes[:'description']
      end

      if attributes.key?(:'data')
        if (value = attributes[:'data']).is_a?(Hash)
          self.data = value
        end
      end

      if attributes.key?(:'row_count')
        self.row_count = attributes[:'row_count']
      else
        self.row_count = nil
      end

      if attributes.key?(:'column_count')
        self.column_count = attributes[:'column_count']
      else
        self.column_count = nil
      end

      if attributes.key?(:'sheet_count')
        self.sheet_count = attributes[:'sheet_count']
      else
        self.sheet_count = nil
      end

      if attributes.key?(:'is_public')
        self.is_public = attributes[:'is_public']
      else
        self.is_public = nil
      end

      if attributes.key?(:'is_read_only')
        self.is_read_only = attributes[:'is_read_only']
      else
        self.is_read_only = nil
      end

      if attributes.key?(:'file_size')
        self.file_size = attributes[:'file_size']
      end

      if attributes.key?(:'last_accessed_at')
        self.last_accessed_at = attributes[:'last_accessed_at']
      end

      if attributes.key?(:'created_at')
        self.created_at = attributes[:'created_at']
      else
        self.created_at = nil
      end

      if attributes.key?(:'updated_at')
        self.updated_at = attributes[:'updated_at']
      else
        self.updated_at = nil
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @id.nil?
        invalid_properties.push('invalid value for "id", id cannot be nil.')
      end

      if @name.nil?
        invalid_properties.push('invalid value for "name", name cannot be nil.')
      end

      if @row_count.nil?
        invalid_properties.push('invalid value for "row_count", row_count cannot be nil.')
      end

      if @column_count.nil?
        invalid_properties.push('invalid value for "column_count", column_count cannot be nil.')
      end

      if @sheet_count.nil?
        invalid_properties.push('invalid value for "sheet_count", sheet_count cannot be nil.')
      end

      if @is_public.nil?
        invalid_properties.push('invalid value for "is_public", is_public cannot be nil.')
      end

      if @is_read_only.nil?
        invalid_properties.push('invalid value for "is_read_only", is_read_only cannot be nil.')
      end

      if @created_at.nil?
        invalid_properties.push('invalid value for "created_at", created_at cannot be nil.')
      end

      if @updated_at.nil?
        invalid_properties.push('invalid value for "updated_at", updated_at cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @id.nil?
      return false if @name.nil?
      return false if @row_count.nil?
      return false if @column_count.nil?
      return false if @sheet_count.nil?
      return false if @is_public.nil?
      return false if @is_read_only.nil?
      return false if @created_at.nil?
      return false if @updated_at.nil?
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] id Value to be assigned
    def id=(id)
      if id.nil?
        fail ArgumentError, 'id cannot be nil'
      end

      @id = id
    end

    # Custom attribute writer method with validation
    # @param [Object] name Value to be assigned
    def name=(name)
      if name.nil?
        fail ArgumentError, 'name cannot be nil'
      end

      @name = name
    end

    # Custom attribute writer method with validation
    # @param [Object] row_count Value to be assigned
    def row_count=(row_count)
      if row_count.nil?
        fail ArgumentError, 'row_count cannot be nil'
      end

      @row_count = row_count
    end

    # Custom attribute writer method with validation
    # @param [Object] column_count Value to be assigned
    def column_count=(column_count)
      if column_count.nil?
        fail ArgumentError, 'column_count cannot be nil'
      end

      @column_count = column_count
    end

    # Custom attribute writer method with validation
    # @param [Object] sheet_count Value to be assigned
    def sheet_count=(sheet_count)
      if sheet_count.nil?
        fail ArgumentError, 'sheet_count cannot be nil'
      end

      @sheet_count = sheet_count
    end

    # Custom attribute writer method with validation
    # @param [Object] is_public Value to be assigned
    def is_public=(is_public)
      if is_public.nil?
        fail ArgumentError, 'is_public cannot be nil'
      end

      @is_public = is_public
    end

    # Custom attribute writer method with validation
    # @param [Object] is_read_only Value to be assigned
    def is_read_only=(is_read_only)
      if is_read_only.nil?
        fail ArgumentError, 'is_read_only cannot be nil'
      end

      @is_read_only = is_read_only
    end

    # Custom attribute writer method with validation
    # @param [Object] created_at Value to be assigned
    def created_at=(created_at)
      if created_at.nil?
        fail ArgumentError, 'created_at cannot be nil'
      end

      @created_at = created_at
    end

    # Custom attribute writer method with validation
    # @param [Object] updated_at Value to be assigned
    def updated_at=(updated_at)
      if updated_at.nil?
        fail ArgumentError, 'updated_at cannot be nil'
      end

      @updated_at = updated_at
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          id == o.id &&
          provider == o.provider &&
          account_id == o.account_id &&
          owner_user_id == o.owner_user_id &&
          name == o.name &&
          description == o.description &&
          data == o.data &&
          row_count == o.row_count &&
          column_count == o.column_count &&
          sheet_count == o.sheet_count &&
          is_public == o.is_public &&
          is_read_only == o.is_read_only &&
          file_size == o.file_size &&
          last_accessed_at == o.last_accessed_at &&
          created_at == o.created_at &&
          updated_at == o.updated_at
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [id, provider, account_id, owner_user_id, name, description, data, row_count, column_count, sheet_count, is_public, is_read_only, file_size, last_accessed_at, created_at, updated_at].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
