=begin
#SpatioAPI

#The REST API that owns every resource in your Spatio workspace: notes, sheets, slides, tasks, calendar events, mail, chat, files, and contacts. SpatioMCP wraps this API; Spatio Desktop reads from it. You can call it directly from your own code.  All requests must be authenticated with a Personal Access Token (`Authorization: Bearer pat_...`) or an OAuth 2.1 access token, and use HTTPS.  Official SDKs (MIT, generated from this spec on every release):  - TypeScript: https://github.com/spatio-labs/spatio-ts (`npm install @spatio/sdk-ts`) - Python: https://github.com/spatio-labs/spatio-py (`pip install spatio-sdk`) - Go: https://github.com/spatio-labs/spatio-go (`go get github.com/spatio-labs/spatio-go`)  This specification is generated from the platform-service Go source on every push to `main`. The spec, not hand-written documentation, is the source of truth: server stubs and SDKs are generated from it, and any drift between the spec and the running service fails CI. 

The version of the OpenAPI document: v1
Contact: hello@spatio.app
Generated by: https://openapi-generator.tech
Generator version: 7.22.0

=end

require 'date'
require 'time'

module Spatio
  # Inline formatting flags for a `RichTextObject`.
  class TextAnnotations < ApiModelBase
    attr_accessor :bold

    attr_accessor :italic

    attr_accessor :strikethrough

    attr_accessor :underline

    attr_accessor :code

    attr_accessor :color

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'bold' => :'bold',
        :'italic' => :'italic',
        :'strikethrough' => :'strikethrough',
        :'underline' => :'underline',
        :'code' => :'code',
        :'color' => :'color'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'bold' => :'Boolean',
        :'italic' => :'Boolean',
        :'strikethrough' => :'Boolean',
        :'underline' => :'Boolean',
        :'code' => :'Boolean',
        :'color' => :'String'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `Spatio::TextAnnotations` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `Spatio::TextAnnotations`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'bold')
        self.bold = attributes[:'bold']
      else
        self.bold = nil
      end

      if attributes.key?(:'italic')
        self.italic = attributes[:'italic']
      else
        self.italic = nil
      end

      if attributes.key?(:'strikethrough')
        self.strikethrough = attributes[:'strikethrough']
      else
        self.strikethrough = nil
      end

      if attributes.key?(:'underline')
        self.underline = attributes[:'underline']
      else
        self.underline = nil
      end

      if attributes.key?(:'code')
        self.code = attributes[:'code']
      else
        self.code = nil
      end

      if attributes.key?(:'color')
        self.color = attributes[:'color']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @bold.nil?
        invalid_properties.push('invalid value for "bold", bold cannot be nil.')
      end

      if @italic.nil?
        invalid_properties.push('invalid value for "italic", italic cannot be nil.')
      end

      if @strikethrough.nil?
        invalid_properties.push('invalid value for "strikethrough", strikethrough cannot be nil.')
      end

      if @underline.nil?
        invalid_properties.push('invalid value for "underline", underline cannot be nil.')
      end

      if @code.nil?
        invalid_properties.push('invalid value for "code", code cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @bold.nil?
      return false if @italic.nil?
      return false if @strikethrough.nil?
      return false if @underline.nil?
      return false if @code.nil?
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] bold Value to be assigned
    def bold=(bold)
      if bold.nil?
        fail ArgumentError, 'bold cannot be nil'
      end

      @bold = bold
    end

    # Custom attribute writer method with validation
    # @param [Object] italic Value to be assigned
    def italic=(italic)
      if italic.nil?
        fail ArgumentError, 'italic cannot be nil'
      end

      @italic = italic
    end

    # Custom attribute writer method with validation
    # @param [Object] strikethrough Value to be assigned
    def strikethrough=(strikethrough)
      if strikethrough.nil?
        fail ArgumentError, 'strikethrough cannot be nil'
      end

      @strikethrough = strikethrough
    end

    # Custom attribute writer method with validation
    # @param [Object] underline Value to be assigned
    def underline=(underline)
      if underline.nil?
        fail ArgumentError, 'underline cannot be nil'
      end

      @underline = underline
    end

    # Custom attribute writer method with validation
    # @param [Object] code Value to be assigned
    def code=(code)
      if code.nil?
        fail ArgumentError, 'code cannot be nil'
      end

      @code = code
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          bold == o.bold &&
          italic == o.italic &&
          strikethrough == o.strikethrough &&
          underline == o.underline &&
          code == o.code &&
          color == o.color
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [bold, italic, strikethrough, underline, code, color].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
